# GitHub Action f체r Hugo Deployment
name: Deploy Hugo site to Pages

on:
  # L채uft bei jedem Push auf den Haupt-Branch
  push:
    branches: ["main"]

  # Erlaubt das manuelle Starten 체ber das "Actions" Tab
  workflow_dispatch:

# Berechtigungen f체r das Deployment setzen
permissions:
  contents: read
  pages: write
  id-token: write

# Verhindert, dass mehrere Deployments gleichzeitig laufen
concurrency:
  group: "pages"
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  # Build-Job
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.121.0 # Hier kannst du deine Hugo-Version anpassen
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive # Wichtig, falls dein Theme ein Submodul ist
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: ${{ env.HUGO_VERSION }}
          extended: true # Falls du SCSS/SASS in deinem Theme nutzt

      - name: Build with Hugo
        run: |
          hugo \
            --gc \
            --minify \
            --baseURL "${{ steps.pagesconfig.outputs.base_url }}/"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  # Deploy-Job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
